/**
 * 포토이즘 PoC 데모 시나리오 상수 (plan 0008).
 *
 * 데모 가이드 7단계에서 보여줄 고정 시나리오. 2단계(설문 설계)·3단계(데이터 수집)는
 * 질문지 미리보기 + mock 수집 수치만 노출하고 실제 데이터는 별도 수집한다는 설정.
 */

export const DEMO_COMPANY = '포토이즘';

export const DEMO_BRIEF = {
  company: '포토이즘',
  objective: '재방문율 저하 원인 진단 및 회복 액션 도출',
  topic: '포토이즘 셀프 사진관, 왜 다시 찾지 않게 될까?',
  target: '최근 6개월 내 셀프 사진관 1회 이상 이용한 20·30대',
  useCase: '리텐션 개선 캠페인 기획과 매장 운영 개선에 활용',
  background:
    '포토이즘은 최근 분기 재방문율이 직전 분기 대비 하락했습니다. 신규 방문은 유지되지만 ' +
    '재방문으로 이어지지 않는 원인을 진단하고, 리텐션을 회복할 액션을 도출하고자 합니다.',
} as const;

/** 설문 렌즈(L1~L6+통제) 한국어 라벨 — 질문 관리 화면의 접기 섹션 제목. */
export const SURVEY_LENS_LABELS: Record<string, string> = {
  L1: "경제적 합리성",
  L2: "의사결정 스타일",
  L3: "동기 구조",
  L4: "사회적 영향",
  L5: "가치 사슬",
  L6: "시간 지향",
  C: "통제·인구통계",
};

/**
 * 2단계 — 설문 2종 + 인터뷰 1종 (실제 적용 문항 전체).
 * 설문 1: Twin-2K-500 한국화(Toubia 2025) — 범용 6-Lens 심리·행동 배터리(267문항).
 * 설문 2: 위 척도를 포토이즘(셀프 사진관) 맥락으로 변형한 도메인 특화 설문(82문항).
 * 문항은 실제 응답자에게 제시된 원본이며, 화면에서는 렌즈별로 접어서 본다.
 */
export const DEMO_SURVEYS = [
  {
    key: 'mindlens',
    title: '기본 소비자 특성 설문',
    desc: '소비 성향·의사결정·가치관을 폭넓게 측정하는 표준 문항 (검증된 심리척도 기반)',
    note: '주제와 무관하게 적용되는 공통 문항으로, AI 소비자의 성향 점수의 토대가 됩니다. 렌즈(L1~L6·통제)별로 접어서 볼 수 있어요.',
    items: [
      { lens: "L1", scaleName: "Risk Aversion (위험 회피)", scale: "선택", q: "좌측 = \"50% 확률로 6,000원, 50% 확률로 0원\"인 추첨. 우측 = 확실한 금액." },
      { lens: "L1", scaleName: "Risk Aversion (위험 회피)", scale: "선택", q: "좌측 = \"50% 확률로 8,000원, 50% 확률로 2,000원\"인 추첨. 우측 = 확실한 금액." },
      { lens: "L1", scaleName: "Risk Aversion (위험 회피)", scale: "선택", q: "좌측 = \"50% 확률로 10,000원, 50% 확률로 0원\"인 추첨. 우측 = 확실한 금액." },
      { lens: "L1", scaleName: "Loss Aversion (손실 회피)", scale: "선택", q: "좌측 = \"50% 확률로 −6,000원 손실, 50% 확률로 0원\". 우측 = 확실한 손실." },
      { lens: "L1", scaleName: "Loss Aversion (손실 회피)", scale: "선택", q: "좌측 = \"50% 확률로 −8,000원 손실, 50% 확률로 −2,000원 손실\". 우측 = 확실한 손실." },
      { lens: "L1", scaleName: "Loss Aversion (손실 회피)", scale: "선택", q: "좌측 = \"50% 확률로 −10,000원 손실, 50% 확률로 0원\". 우측 = 확실한 손실." },
      { lens: "L1", scaleName: "Loss Aversion (손실 회피)", scale: "선택", q: "혼합 추첨 — \"50% 확률로 8,000원 손실, 50% 확률로 x원 이득\"인 추첨과 \"0원(현상유지)\" 중 선택." },
      { lens: "L1", scaleName: "Mental Accounting (심적 회계)", scale: "2점 척도", q: "다음 두 사람 중 누가 더 행복했을까요?" },
      { lens: "L1", scaleName: "Mental Accounting (심적 회계)", scale: "2점 척도", q: "다음 두 사람 중 누가 더 화났을까요?" },
      { lens: "L1", scaleName: "Mental Accounting (심적 회계)", scale: "2점 척도", q: "다음 두 사람 중 누가 더 행복했을까요?" },
      { lens: "L1", scaleName: "Mental Accounting (심적 회계)", scale: "선택(MPL)", q: "다음 두 사람 중 누가 더 화났을까요?" },
      { lens: "L1", scaleName: "Tightwad–Spendthrift (구두쇠–낭비벽)", scale: "3점 척도", q: "본인의 소비 습관을 가장 잘 설명하는 것은 어느 쪽에 가깝나요?" },
      { lens: "L1", scaleName: "Tightwad–Spendthrift (구두쇠–낭비벽)", scale: "5점 척도", q: "Q2-a. \"어떤 사람들은 지출을 절제하기 어려워합니다. 옷·외식·여행 같은 데 안 쓰는 게 더 나은 상황에서도 종종 돈을 씁니다.\" 이 설명이 본인에게 얼마나 잘 맞나요? (즉, 지출을 절제하기 어렵나요?)" },
      { lens: "L1", scaleName: "Tightwad–Spendthrift (구두쇠–낭비벽)", scale: "5점 척도", q: "Q2-b. \"어떤 사람들은 돈 쓰는 것 자체를 어려워합니다. 돈 쓰는 게 불안해서, 써야 할 곳에도 종종 쓰지 못합니다.\" 이 설명이 본인에게 얼마나 잘 맞나요? (즉, 돈 쓰는 게 어려운가요?)" },
      { lens: "L1", scaleName: "Tightwad–Spendthrift (구두쇠–낭비벽)", scale: "5점 척도", q: "다음 두 쇼핑객 중 본인은 누구와 더 비슷한가요? A씨: 친구와 쇼핑몰에 갔는데 백화점이 \"오늘 하루 세일\"을 한다. 살 게 없는 걸 알면서도 결국 약 10만원어치를 산다. B씨: 같은 상황에서, 좋은 가격에 살 기회임을 알면서도 돈 쓸 생각만 하면 결국 사지 못한다." },
      { lens: "L1", scaleName: "Framing Problem (프레이밍 문제)", scale: "6점 척도", q: "우리나라가 600명을 사망시킬 것으로 예상되는 특이한 전염병 발발에 대비하고 있다고 가정해 보세요. 이 전염병에 대처하는 두 가지 대안 프로그램이 제안되었습니다. • 프로그램 A: 400명이 죽을 것이다. • 프로그램 B: 1/3 확률로 아무도 죽지 않고, 2/3 확률로 600명이 죽는다. 어느 쪽을 선호하시나요?" },
      { lens: "L1", scaleName: "Absolute vs Relative Savings (절대 vs 상대 절약)", scale: "2점 척도", q: "3만원짜리 계산기를 사러 갔다고 해 보세요. 점원이 \"같은 제품을 다른 매장에서 2만원에 세일하고 있다\"고 알려줍니다. 다른 매장은 차로 10분 거리에 있습니다. 그 매장으로 차를 타고 가시겠습니까?" },
      { lens: "L2", scaleName: "Maximization Scale (극대화 척도)", scale: "5점 동의", q: "차에서 라디오를 들을 때, 지금 듣는 게 그럭저럭 괜찮아도 더 좋은 게 나오는지 보려고 자주 다른 채널을 돌려본다." },
      { lens: "L2", scaleName: "Maximization Scale (극대화 척도)", scale: "5점 동의", q: "지금 직장에 아무리 만족하더라도, 더 나은 기회가 있는지 늘 살펴보는 게 옳다고 생각한다." },
      { lens: "L2", scaleName: "Maximization Scale (극대화 척도)", scale: "5점 동의", q: "친구한테 줄 선물을 고르는 일이 어렵다고 자주 느낀다." },
      { lens: "L2", scaleName: "Maximization Scale (극대화 척도)", scale: "5점 동의", q: "쇼핑할 때 정말 마음에 드는 옷을 찾기가 어렵다." },
      { lens: "L2", scaleName: "Maximization Scale (극대화 척도)", scale: "5점 동의", q: "무엇을 하든 나는 스스로에게 가장 높은 기준을 적용한다." },
      { lens: "L2", scaleName: "Maximization Scale (극대화 척도)", scale: "5점 동의", q: "차선책으로는 만족이 안 된다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "불확실한 상황을 좋아하지 않는다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "여러 가지로 답할 수 있는 질문은 싫다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "정해진 시간에 잘 정돈된 삶이 내 성격에 잘 맞는다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "내 인생에 일어난 일들의 이유를 이해하지 못하면 불편하다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "한 사람이 다른 모든 구성원이 믿는 것에 동의하지 않으면 짜증이 난다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "어떤 상황에 들어갈 때 무엇을 기대해야 할지 모르는 게 싫다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "결정을 내리고 나면 마음이 놓인다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "문제에 부딪히면 빨리 해결책을 찾고 싶어 안달이 난다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "바로 해결책이 떠오르지 않으면 금세 참을성이 없어지고 짜증이 난다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "예측이 안 되는 행동을 하는 사람들과 같이 있는 게 싫다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "어떤 사람의 말이 여러 의미로 해석될 수 있을 때 그게 싫다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "일관된 생활 패턴을 만들면 인생이 더 즐거워진다고 생각한다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "명확하고 잘 짜인 생활 방식이 좋다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "내 의견을 정하기 전에 다른 사람들의 의견을 여러 개 살펴보는 편은 아니다." },
      { lens: "L2", scaleName: "Need for Closure Scale (인지적 종결 욕구)", scale: "5점 동의", q: "예측할 수 없는 상황은 싫다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "단순한 문제보다 복잡한 문제를 더 좋아한다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "생각을 많이 해야 하는 상황을 떠맡는 걸 좋아한다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "생각하는 일은 내게 즐거움이 아니다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "사고력이 도전받는 일보다, 머리를 별로 안 써도 되는 일을 하고 싶다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "깊이 생각해야 할 일이 생길 것 같으면 미리 피하려고 한다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "오랜 시간 깊이 고민하는 데서 만족을 느낀다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "꼭 필요한 만큼만 생각하는 편이다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "장기 프로젝트보다 작고 일상적인 것에 대해 생각하는 게 더 좋다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "한번 익히고 나면 별 생각 없이 할 수 있는 일이 좋다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "생각을 통해 정상에 오른다는 발상이 매력적으로 느껴진다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "새로운 해결책을 만들어내는 일이 정말 즐겁다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "새로운 사고방식을 배우는 건 별로 흥미가 없다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "풀어야 할 문제로 가득한 인생이 더 좋다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "추상적으로 사고한다는 발상이 마음에 든다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "적당히 중요하지만 머리를 별로 안 쓰는 일보다, 어렵고 중요한 지적인 일을 더 좋아한다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "정신적으로 힘든 일을 끝내고 나면 만족보다 안도감이 먼저 든다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "결과만 잘 나오면 된다. 어떻게/왜 그렇게 되는지는 별로 신경 쓰지 않는다." },
      { lens: "L2", scaleName: "Need for Cognition Scale (인지 욕구)", scale: "5점 동의", q: "나와 직접 관련 없는 일이라도 결국 깊이 생각하게 된다." },
      { lens: "L2", scaleName: "Cognitive Reflection Test (CRT)", scale: "주관식", q: "수아의 어머니에게는 딸이 셋 있습니다. 첫째는 \"봄\", 둘째는 \"여름\"이라는 이름입니다. 셋째 딸의 이름은 무엇일까요?" },
      { lens: "L2", scaleName: "Cognitive Reflection Test (CRT)", scale: "주관식", q: "가로 1m, 세로 1m, 깊이 1m인 구덩이 안에 흙이 몇 입방미터 들어 있을까요?" },
      { lens: "L2", scaleName: "Cognitive Reflection Test (CRT)", scale: "주관식", q: "달리기 경주에서 2등을 추월했다면, 본인은 지금 몇 등인가요?" },
      { lens: "L2", scaleName: "Cognitive Reflection Test (CRT)", scale: "주관식", q: "어떤 농부에게 양 15마리가 있었는데, 8마리만 남고 모두 죽었습니다. 몇 마리가 남았나요?" },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "다른 사람의 지시 없이 일하는 걸 더 좋아한다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "규칙과 규정은 내게 도움이 되고 필요하다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "내게 주어진 의무를 다하는 일이 매우 중요하다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "보통은 문제를 창의적으로 해결한다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "어떤 일이든 매우 꼼꼼히 검토하고 확인하는 게 거슬리지 않는다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "새로운 방식으로 일하는 걸 좋아한다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "일은 가능한 한 정확하게, 실수 없이 하려고 한다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "다양한 것을 시도해 보는 걸 좋아하고, 종종 좋은 결과를 낸다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "내가 이룬 성과가 다른 사람에게 인정받고 평가받는 게 중요하다." },
      { lens: "L3", scaleName: "Regulatory Focus Scale (조절초점 척도)", scale: "7점 척도", q: "다른 사람이 나에게 무엇을 기대하는지 자주 생각한다." },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "부 (WEALTH) — 재정적 성공, 풍요" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "쾌락 (PLEASURE) — 인생의 즐거움과 향유를 충분히 누리는 것" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "용서 (FORGIVENESS) — 타인의 잘못을 용서함, 너그러움" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "영향력 (INFLUENCE) — 사람과 사건에 영향을 미침" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "신뢰 (TRUST) — 자기 말을 지킴, 타인의 선의를 가정함" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "유능함 (COMPETENCE) — 숙달, 능력, 효과성을 보임" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "겸손 (HUMILITY) — 타인을 존중함, 자신을 낮춤" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "성취 (ACHIEVEMENT) — 높은 목표 달성" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "이타심 (ALTRUISM) — 도움이 필요한 타인을 도움" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "야망 (AMBITION) — 큰 포부, 기회 포착" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "충실 (LOYALTY) — 친구·가족·집단에 대한 헌신" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "예의 (POLITENESS) — 예의 바름, 좋은 매너" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "권력 (POWER) — 타인에 대한 통제, 지배" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "조화 (HARMONY) — 좋은 관계, 균형, 평온" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "흥분 (EXCITEMENT) — 모험·위험·자극적 라이프스타일 추구" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "정직 (HONESTY) — 진실됨, 진정성" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "연민 (COMPASSION) — 타인을 돌보고 친절을 베풂" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "지위 (STATUS) — 높은 사회적 위치, 폭넓은 존경" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "교양 (CIVILITY) — 타인에 대한 사려와 존중" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "자율 (AUTONOMY) — 독립적, 타인의 통제로부터 자유로움" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "평등 (EQUALITY) — 모두가 동등한 인권과 기회를 가짐" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "인정 (RECOGNITION) — 주목받음, 유명해짐, 존경받음" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "전통 (TRADITION) — 가족·문화 가치를 존중함" },
      { lens: "L3", scaleName: "Agentic vs Communal Values (가치)", scale: "3점 척도", q: "우월 (SUPERIORITY) — 경쟁자를 이기고 정상에 섬" },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "복제할 수 없는 나만의 이미지를 만들기 위해 소유물들을 자주 조합해서 쓴다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "독창적인 걸 좋아해서, 평범한 제품의 더 흥미로운 버전을 자주 찾아본다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "특별한 제품이나 브랜드를 사서 나만의 독특함을 적극적으로 만들어 간다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "흥미롭고 특이한 제품을 알아보는 안목이 차별적인 이미지를 만드는 데 도움이 된다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "내가 사는 제품과 사용 상황에서, 관습이나 통념을 깬 적이 있다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "무엇을 사야 하고 무엇을 가져야 한다는 사회적 암묵적 규칙을 자주 어겨 왔다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "어떤 제품을 언제, 어떻게 써야 하느냐에 대한 사회적 통념에 종종 반하는 행동을 했다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "주변 사람들이 받아들이지 않을 만한 걸 사서 그들의 일반적 취향에 도전하는 게 즐겁다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "내가 가진 제품이 일반인들 사이에서 인기가 많아지면, 점점 덜 쓰게 된다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "보통 사람들이 사는 걸로 알려진 제품이나 브랜드는 일부러 피하려고 한다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "일반적으로, 누구나 흔히 사는 제품이나 브랜드는 별로 좋아하지 않는다." },
      { lens: "L3", scaleName: "Need for Uniqueness Scale (독특성 욕구)", scale: "5점 동의", q: "어떤 제품이나 브랜드가 일반인들 사이에서 흔해질수록, 사고 싶은 마음이 줄어든다." },
      { lens: "L3", scaleName: "Selves Questionnaire (자기 차이 질문)", scale: "주관식", q: "(이상적 자기) 본인이 되고 싶은 사람의 모습을 적어 주세요. 즉, 이상적으로 갖추고 싶은 특성과 행동, 자신에 대한 궁극적 목표를 적어 주세요." },
      { lens: "L3", scaleName: "Selves Questionnaire (자기 차이 질문)", scale: "주관식", q: "(의무적 자기) 본인이 되어야 하는 사람의 모습을 적어 주세요. 즉, 본인의 책임과 다른 사람들이 본인에게 기대하는 것에 비추어, 본인이 가지고 있어야 할 특성과 행동을 적어 주세요." },
      { lens: "L3", scaleName: "Selves Questionnaire (자기 차이 질문)", scale: "주관식", q: "(실제 자기) 본인이 실제로 어떤 사람인지 적어 주세요. 실제로 가지고 있는 특성과 행동을 적어 주세요." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "유행하는 옷이나 스타일을 살 때, 친구들이 좋게 봐줄 거라는 확신이 있기 전엔 잘 안 산다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "내가 사는 제품·브랜드를 다른 사람들이 좋아하는 것이 내겐 중요하다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "제품을 살 때, 보통은 다른 사람들이 좋게 평가할 만한 브랜드를 고른다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "다른 사람이 내가 쓰는 모습을 볼 수 있는 제품은, 그들이 기대할 만한 브랜드로 사는 편이다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "어떤 브랜드·제품이 다른 사람에게 좋은 인상을 주는지 알고 싶어 한다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "다른 사람들이 많이 사는 제품·브랜드를 같이 사면, 어딘가에 소속된 느낌이 든다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "닮고 싶은 사람이 있으면, 그 사람이 쓰는 것과 같은 브랜드를 따라 사려고 하는 편이다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "다른 사람과 같은 제품·브랜드를 사면서 그들과 비슷해진다는 느낌을 받을 때가 많다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "올바른 제품이나 브랜드를 사기 위해, 다른 사람들이 무엇을 사서 쓰는지 자주 살펴본다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "어떤 제품에 대해 잘 모를 때는, 친구들에게 그 제품에 대해 자주 물어본다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "어떤 카테고리에서 가장 나은 제품을 고를 때, 다른 사람들의 의견을 자주 구한다." },
      { lens: "L4", scaleName: "Susceptibility to Interpersonal Influence (SUSCEP)", scale: "5점 동의", q: "제품을 사기 전에 친구나 가족에게서 그 제품에 대한 정보를 자주 모으는 편이다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "사회적 상황에서, 다른 행동이 필요하다고 느끼면 내 행동을 바꿀 수 있다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "주고 싶은 인상에 따라, 사람들에게 비치는 내 모습을 조절할 수 있다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "지금 보여주고 있는 이미지가 잘 안 통한다고 느끼면, 통하는 다른 이미지로 쉽게 바꿀 수 있다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "다른 사람과 다른 상황에 맞춰 내 행동을 바꾸는 게 어렵다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "어떤 상황에 처하든 그 상황이 요구하는 것에 맞춰 내 행동을 조절할 수 있다는 걸 알고 있다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "유리한 상황에서도, 좋은 인상을 만들어내는 게 어렵다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "그 상황에서 무엇이 필요한지 알면, 내 행동을 거기에 맞추는 게 쉽다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "사람들의 진짜 감정을 표정만 봐도 정확히 알아챌 때가 많다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "대화 중에, 상대방 표정에서 일어나는 아주 작은 변화도 잘 알아차린다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "다른 사람의 감정과 의도를 직관으로 파악하는 능력이 꽤 좋다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "사람들이 웃는 시늉을 해도, 그들이 어떤 농담을 무례하다고 느끼는지 알아챌 수 있다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "내가 부적절한 말을 했을 때, 상대방 눈빛만 봐도 그걸 알아차릴 수 있다." },
      { lens: "L4", scaleName: "Self-Monitoring Scale (자기 감시)", scale: "6점 척도", q: "누가 거짓말을 하면, 그 사람의 표현 방식에서 곧바로 알아차리는 경우가 많다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "다른 사람에게 의지하기보다 나 자신에게 의지하는 게 더 좋다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "거의 대부분의 시간 동안 나 자신에게 의지하며, 다른 사람에게는 거의 기대지 않는다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "내 일은 내가 알아서 하는 편이다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "다른 사람과 무관한, 나만의 개인적 정체성이 매우 중요하다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "다른 사람보다 일을 잘 해내는 게 내게 중요하다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "이기는 것이 전부다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "경쟁은 자연의 법칙이다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "다른 사람이 나보다 더 잘하면, 긴장되고 자극이 된다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "동료가 상을 받으면, 나도 자랑스럽다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "동료의 안녕(잘 지내는 것)이 내게 중요하다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "내가 즐거움을 느끼는 건 다른 사람들과 시간을 보낼 때다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "다른 사람들과 협력할 때 기분이 좋다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "부모와 자식은 가능한 한 함께 있어야 한다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "내가 원하는 걸 희생해야 하더라도, 가족을 돌보는 일은 내 의무다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "어떤 희생이 필요해도, 가족 구성원은 함께 뭉쳐 있어야 한다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism Scale", scale: "5점 동의", q: "내가 속한 집단의 결정을 존중하는 게 중요하다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "누가 격려해 주지 않으면 일을 끝까지 해내기 어려울 때가 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "내 뜻대로 안 되면 화가 날 때가 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "내 능력을 너무 낮게 봐서 어떤 일을 포기한 적이 몇 번 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "권위 있는 사람이 옳다는 걸 알면서도, 그들에게 반항하고 싶었던 적이 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "내가 누구와 이야기하든, 나는 항상 잘 들어주는 사람이다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "누군가를 이용한 적이 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "내가 실수했을 때 늘 인정하려고 한다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "용서하고 잊기보다 보복하려고 한 적이 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "거슬리는 사람한테도 나는 항상 정중하다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "내 의견과 다른 의견을 내는 사람한테 짜증 난 적이 한 번도 없다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "다른 사람의 행운을 꽤 부러워한 적이 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "부탁하는 사람들 때문에 짜증 날 때가 있다." },
      { lens: "L4", scaleName: "Social Desirability Scale (사회적 바람직성)", scale: "2점 척도", q: "누군가의 감정을 상하게 할 만한 말을 일부러 한 적이 한 번도 없다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구의 감정은 내게 별 영향을 주지 않는다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "어떤 일로 슬퍼하는 친구와 같이 있다 보면, 보통 나도 슬퍼진다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구가 무언가를 잘 해냈을 때 그가 느끼는 행복을 이해할 수 있다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "잘 만든 공포 영화의 등장인물을 볼 때 같이 무서워진다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "다른 사람의 감정에 쉽게 휩쓸린다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구가 언제 무서워하는지 알기 어렵다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "다른 사람이 우는 걸 봐도 내가 슬퍼지지는 않는다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "다른 사람의 감정은 내게 별로 거슬리지 않는다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "누군가가 우울할 때 보통 그 사람의 기분을 이해할 수 있다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구가 언제 무서워하는지 보통 알아챈다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "TV나 영화에서 슬픈 장면을 볼 때 자주 슬퍼진다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "사람들이 말로 표현하기 전에도 그들의 감정을 알아챌 때가 많다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "화난 사람을 봐도 내 감정에는 영향이 없다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "사람들이 언제 기분이 좋은지 보통 알아챈다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "무서워하는 친구들과 같이 있으면 나도 무서워지는 편이다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구가 언제 화났는지 보통 빠르게 알아차린다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구의 감정에 자주 휩쓸린다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구가 불행한 일을 겪어도 내겐 아무런 감정도 일지 않는다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구의 감정을 잘 모를 때가 많다." },
      { lens: "L4", scaleName: "Empathy Scale — Basic Empathy in Adults (BES-A)", scale: "5점 동의", q: "친구가 언제 행복한지 알아내기 어렵다." },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 1] 기업 대상 탄소세 도입 (탄소 배출량 기준 과세)" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 2] 종합부동산세 과세 대상 및 세율 강화" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 3] 외국인 노동자 고용 허가제 확대 (인력 부족 업종 대상)" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 4] 건강보험 보장률 80% 이상으로 확대 (필수 의료비 본인 부담 경감)" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 5] 65세 이상 지하철 무임승차 제도 단계적 폐지" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 6] 다문화 가정 자녀 교육·생활 지원 예산 확대" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 7] 유급 출산휴가 6개월 의무화 (남녀 모두)" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 8] 순자산 100억원 이상 보유자 대상 부유세 신설" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 9] 미등록 외국인 체류자 단속 및 강제출국 강화" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "5점 찬반", q: "[정책 10] 국민연금 보험료율 단계적 인상 (지속가능성 확보)" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 1] 기업 대상 탄소세 도입 (탄소 배출량 기준 과세) — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 2] 종합부동산세 과세 대상 및 세율 강화 — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 3] 외국인 노동자 고용 허가제 확대 (인력 부족 업종 대상) — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 4] 건강보험 보장률 80% 이상으로 확대 (필수 의료비 본인 부담 경감) — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 5] 65세 이상 지하철 무임승차 제도 단계적 폐지 — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 6] 다문화 가정 자녀 교육·생활 지원 예산 확대 — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 7] 유급 출산휴가 6개월 의무화 (남녀 모두) — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 8] 순자산 100억원 이상 보유자 대상 부유세 신설 — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 9] 미등록 외국인 체류자 단속 및 강제출국 강화 — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "False Consensus (잘못된 합의)", scale: "선택", q: "[정책 10] 국민연금 보험료율 단계적 인상 (지속가능성 확보) — 우리나라 성인 중 몇 %가 지지할 것이라고 생각하시나요?" },
      { lens: "L4", scaleName: "Dictator Game (독재자 게임)", scale: "5점 척도", q: "본인이 5,000원을 받았고, 본인과 다른 (익명의) 사람 사이에 그 돈을 어떻게 나눌지 결정해야 한다고 가정해 주세요. 본인이 분배 방식을 정하며, 상대방은 본인의 제안을 그대로 받아들여야 합니다. 본인은 얼마를 가지고, 얼마를 상대에게 보내겠습니까?" },
      { lens: "L4", scaleName: "Dictator Game (독재자 게임)", scale: "주관식", q: "돈을 얼마나 가지고 얼마를 보낼지 결정할 때 어떤 생각을 했는지 자유롭게 적어 주세요. 한 박스에 한 가지 생각만, 첫 번째 떠오른 생각부터 순서대로 작성해 주세요. (응답 선택 사항)" },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "물건을 많이 쌓아두는 걸 피한다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "내가 가지고 있는 물건의 수를 일부러 제한하려 한다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "소유에 있어서 \"적을수록 좋다\"고 생각한다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "물건을 과하게 사들이는 걸 적극적으로 피한다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "시각적으로 단순한 환경에 끌린다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "디자인은 단순한 게 더 좋다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "집의 분위기를 매우 단정하고 깔끔하게 유지하려 한다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "공간을 채우기보다 시각적으로 비워두는 걸 선호한다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "내가 무엇을 가지고 있는지 항상 의식하고 있다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "내가 가진 물건들은 신중하게 골라 모은 것이다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "무엇을 가질지 신중하게 고르는 일이 내게 중요하다." },
      { lens: "L5", scaleName: "Consumer Minimalism Scale (소비자 미니멀리즘)", scale: "5점 동의", q: "내 소유물은 의식적으로 선택한 결과물이다." },
      { lens: "L5", scaleName: "Green Values Scale (친환경 가치)", scale: "5점 동의", q: "내가 쓰는 제품이 환경에 해를 끼치지 않는 게 내게 중요하다." },
      { lens: "L5", scaleName: "Green Values Scale (친환경 가치)", scale: "5점 동의", q: "결정을 내릴 때 내 행동이 환경에 미칠 영향을 자주 고려한다." },
      { lens: "L5", scaleName: "Green Values Scale (친환경 가치)", scale: "5점 동의", q: "내 구매 습관은 환경에 대한 걱정에 영향을 받는다." },
      { lens: "L5", scaleName: "Green Values Scale (친환경 가치)", scale: "5점 동의", q: "지구의 자원이 낭비되는 게 걱정된다." },
      { lens: "L5", scaleName: "Green Values Scale (친환경 가치)", scale: "5점 동의", q: "나는 환경에 대해 책임감 있는 사람이라고 생각한다." },
      { lens: "L5", scaleName: "Green Values Scale (친환경 가치)", scale: "5점 동의", q: "더 환경 친화적으로 행동하기 위해서라면 어느 정도 불편은 감수할 의향이 있다." },
      { lens: "L6", scaleName: "Discount Rate (할인율)", scale: "선택", q: "좌측 = \"6주 후 6,000원\". 우측 = \"5주 후 x원\"." },
      { lens: "L6", scaleName: "Discount Rate (할인율)", scale: "선택", q: "좌측 = \"7주 후 8,000원\". 우측 = \"6주 후 x원\"." },
      { lens: "L6", scaleName: "Discount Rate (할인율)", scale: "선택", q: "좌측 = \"7주 후 10,000원\". 우측 = \"5주 후 x원\"." },
      { lens: "L6", scaleName: "Present Bias (현재 편향)", scale: "선택", q: "좌측 = \"1주 후 6,000원\". 우측 = \"지금 x원\"." },
      { lens: "L6", scaleName: "Present Bias (현재 편향)", scale: "선택", q: "좌측 = \"1주 후 8,000원\". 우측 = \"지금 x원\"." },
      { lens: "L6", scaleName: "Present Bias (현재 편향)", scale: "선택", q: "좌측 = \"2주 후 10,000원\". 우측 = \"지금 x원\"." },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "조직적인 (Organized)" },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "효율적인 (Efficient)" },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "체계적인 (Systematic)" },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "실용적인 (Practical)" },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "정리되지 않은 (Disorganized)" },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "엉성한 (Sloppy)" },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "비효율적인 (Inefficient)" },
      { lens: "L6", scaleName: "Conscientiousness Scale Wave 2 (성실성 단축형)", scale: "3점 척도", q: "부주의한 (Careless)" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "17점 척도", q: "거주 지역 (광역시도)" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "2점 척도", q: "출생 시 부여된 성별" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "6점 척도", q: "연령대" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "7점 척도", q: "최종 학력" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "3점 척도", q: "국적 / 인종" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "7점 척도", q: "체류 자격 (외국인의 경우)" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "5점 척도", q: "결혼 상태" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "7점 척도", q: "현재 종교" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "6점 척도", q: "종교 활동 빈도" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "7점 척도", q: "지지 정당 (있다면)" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "7점 척도", q: "월평균 가구 소득 (세전, 가구 합계)" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "5점 척도", q: "정치 이념 자가 평가" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "5점 척도", q: "가구원 수 (본인 포함)" },
      { lens: "C", scaleName: "Demographics (인구통계)", scale: "8점 척도", q: "고용 상태" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "2점 척도", q: "다음 진술이 참(O)인지 거짓(X)인지 답하세요. \"15년 만기 주택담보대출은 30년 만기에 비해 월 납부액이 더 많지만, 대출 기간 전체로 보면 총 이자는 더 적게 낸다.\"" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "4점 척도", q: "본인 예금계좌 이자가 연 1%이고 인플레이션이 연 2%였다고 가정하세요. 1년 후, 이 계좌의 돈으로 살 수 있는 양은:" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "4점 척도", q: "일반적으로 다음 중 시간이 지남에 따라 가격 변동이 가장 큰 자산은?" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "2점 척도", q: "다음 진술이 참(O)인지 거짓(X)인지 답하세요. \"주식형 펀드에 100만원을 투자할 경우, 환매(인출) 시 100만원보다 적게 받을 수도 있다.\"" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "4점 척도", q: "투자자가 자금을 여러 자산에 분산할 경우, 큰 손실을 입을 위험은:" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "4점 척도", q: "긴 기간(예: 10~20년) 동안, 일반적으로 가장 높은 수익을 내는 자산은?" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "2점 척도", q: "다음 진술이 참(O)인지 거짓(X)인지 답하세요. \"연금저축·개인형 IRP 계좌의 적립금은 만 55세 이후 연금 형태로 인출하는 게 세제상 가장 유리하다.\"" },
      { lens: "C", scaleName: "Financial Literacy Test (금융 이해력)", scale: "주관식", q: "신용카드에 300만원의 빚이 있다고 가정합시다. 매달 최소 결제액은 3만원이고, 연 15% APR(월 1.25%)이 부과됩니다. 추가로 신규 사용을 하지 않을 때, 이 빚을 다 갚는 데 몇 년이 걸릴까요?" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "공정한 6면 주사위를 1,000번 굴린다고 상상해 보세요. 1,000번 중 짝수가 나올 횟수는 몇 번이 가장 가능성이 높을까요? (0~1,000)" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "어느 복권에서 1만원 상금이 당첨될 확률이 1%입니다. 1,000명이 각각 한 장씩 사면, 1만원에 당첨되는 사람은 몇 명일까요? (0~1,000)" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "어떤 질병에 걸릴 확률이 \"100명 중 20명\"이라면, 이는 [공란]%의 확률로 그 병에 걸리는 것과 같습니다. (0~100)" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "한 출판사 추첨에서 자동차에 당첨될 확률이 1/1,000입니다. 응모권 중 몇 %가 자동차에 당첨될까요? (0~100)" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "어떤 질병에 걸릴 확률이 10%라면, 1,000명 중 몇 명이 그 병에 걸린다고 예상할 수 있을까요? (0~1,000)" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "기계 5대가 5분에 위젯 5개를 만든다면, 기계 100대가 위젯 100개를 만드는 데 몇 분이 걸릴까요?" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "야구 방망이와 공의 가격을 합치면 11,000원입니다. 방망이는 공보다 10,000원 더 비쌉니다. 공의 가격은 얼마일까요?" },
      { lens: "C", scaleName: "Numeracy Test (수리 능력)", scale: "주관식", q: "한 호수에 수련 잎 군락이 자라고 있습니다. 매일 군락 크기가 두 배가 됩니다. 군락이 호수 전체를 덮는 데 48일이 걸린다면, 호수의 절반을 덮는 데는 며칠이 걸릴까요?" },
    ],
  },
  {
    key: 'domain',
    title: '포토이즘 도메인 특화 설문',
    desc: '동일한 성향 척도를 셀프 사진관 맥락(매장·콘셉트·재방문)으로 변형',
    note: '범용 척도를 포토이즘 상황에 투영해 도메인 행동을 측정합니다.',
    items: [
      { lens: "L1", scaleName: "Risk Aversion (위험 회피)", scale: "선택", q: "매장 영수증 추첨 — 추첨에 응모할지, 확정 할인 쿠폰을 받을지 골라 주세요." },
      { lens: "L1", scaleName: "Mental Accounting (심적 회계)", scale: "2점 척도", q: "다음 두 사람 중 누가 더 행복했을까요?" },
      { lens: "L1", scaleName: "Mental Accounting (심적 회계)", scale: "2점 척도", q: "다음 두 사람 중 누가 더 화났을까요? (두 사람 모두 4장 10,000원 촬영을 마친 상태입니다.)" },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "자주 가는 포토부스 매장이 있어도, 새로 생긴 매장이 있는지 자주 알아본다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "한 매장에 만족해도, 더 분위기·필터·프레임이 좋은 매장이 있는지 자주 비교한다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "사진 찍을 매장을 정할 때, 가능한 한 많은 후보 매장을 비교해 보는 편이다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "사진 콘셉트나 프레임을 결정하기 전에 SNS·블로그에서 사례를 많이 찾아보는 편이다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "친구·연인과 갈 포토부스 매장이나 콘셉트를 고르는 게 자주 어렵게 느껴진다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "사진을 인쇄·SNS 공유하기 전에 여러 후보 사진 중 가장 좋은 한 장을 고르느라 시간이 오래 걸린다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "포토부스에서 정말 마음에 드는 결과물(사진·프레임 조합)을 만들어내는 게 어렵다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "사진을 찍을 때 나는 스스로에게 가장 높은 기준을 적용한다. (완벽함을 추구한다)" },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "한 번 찍은 사진을 보고 나서, 더 좋게 찍을 수 있었다는 생각을 자주 한다." },
      { lens: "L2", scaleName: "Maximization Scale", scale: "5점 동의", q: "사진 결과물이 차선책 정도라면 만족할 수 없다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "포토부스에 갈 때 어떤 콘셉트로 찍을지 미리 정하지 않으면 불안하다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "매장에 도착해서 어떤 분위기·콘셉트일지 모르는 채로 들어가는 게 싫다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "포토부스에서 즉흥적으로 콘셉트를 바꾸는 사람들과 같이 있으면 답답하다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "사진의 분위기·콘셉트가 명확히 정해져 있는 매장을 더 선호한다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "친구·연인과 갈 때마다 같은 포토부스·같은 콘셉트로 가는 게 편하다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "어떤 프레임·옵션으로 갈지 결정을 내리고 나면 마음이 놓인다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "일행이 사진 콘셉트나 프레임을 빨리 정해주지 않으면 답답하다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "같이 간 일행 중 한 명이 사진 콘셉트에 동의하지 않으면 짜증이 난다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "사진을 어떻게 찍을지 결정하기 전에, 일행의 의견을 여러 개 살펴보는 편은 아니다." },
      { lens: "L2", scaleName: "Need for Closure", scale: "5점 동의", q: "사진 옵션·프레임이 너무 많아서 어떻게 해석해도 되는 매장은 부담스럽다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "포토부스 매장 직원 안내 없이 혼자 프레임·콘셉트를 정하는 것을 선호한다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "포토부스 이용 방법(촬영 순서·버튼 조작)이 명확히 안내되어 있으면 안심이 된다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "프레임·필터 조합을 남들이 잘 안 쓰는 방식으로 시도해보는 편이다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "사진을 인쇄하기 전에 미리보기를 꼼꼼히 확인하는 편이다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "포토부스에 갈 때마다 다른 콘셉트나 매장을 시도해보고 싶다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "사진이 조금이라도 흔들리거나 표정이 이상하면 다시 찍으려 한다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "새로 출시된 IP 한정 프레임이나 신규 콘셉트를 적극적으로 써보는 편이다." },
      { lens: "L3", scaleName: "Regulatory Focus", scale: "5점 동의", q: "포토부스에서 찍은 사진이 SNS에서 반응이 좋으면 더 뿌듯하다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "남들이 잘 안 쓰는 프레임·필터 조합으로 나만의 사진 스타일을 만들려 한다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "포토부스에서 기본 프레임보다 독특하거나 색다른 프레임을 찾아보는 편이다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "한정 IP 프레임이나 아티스트 콜라보 프레임을 적극적으로 찾아서 쓰는 편이다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "남들과 다른 콘셉트로 찍은 포토부스 사진이 내 이미지를 잘 표현한다고 느낀다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "포토부스에서 일반적인 포즈나 콘셉트 대신 독특한 방식으로 찍은 적이 있다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "유행하는 포토부스 콘셉트가 있어도 굳이 따르지 않는 편이다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "포토부스는 특정 상황(기념일·여행)에서만 쓴다는 생각에 동의하지 않는다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "주변 사람들이 별로라고 할 것 같아도 내가 좋아하는 콘셉트로 찍는 것을 즐긴다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "내가 자주 쓰던 포토부스 프레임이 갑자기 유행하면, 그 프레임에 흥미가 줄어든다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "포토이즘에서 가장 인기 있는 필터나 프레임은 일부러 피하는 편이다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "포토부스에서 누구나 쓸 것 같은 인기 프레임은 별로 끌리지 않는다." },
      { lens: "L3", scaleName: "Need for Uniqueness", scale: "5점 동의", q: "포토이즘의 특정 프레임이 너무 흔해지면 그 프레임을 쓰고 싶은 마음이 줄어든다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "포토부스에 갈 때, 다른 사람과 같이 가기보다 혼자 가는 게 편할 때가 많다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "사진 찍는 콘셉트나 프레임을 정할 때, 다른 사람 의견보다 내 취향에 따라 정하는 편이다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "다른 사람과 무관한, 나만의 스타일이 담긴 사진이 매우 중요하다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "같이 사진 찍은 사람들 중 내가 가장 잘 나오는 게 내게 중요하다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "SNS에서 누구 사진이 더 많은 반응을 얻는지 비교되는 건 자연스러운 일이다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "다른 사람이 나보다 잘 나온 것 같으면 신경쓰인다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "내가 사진 찍는 게 즐거운 건, 다른 사람들과 함께 시간을 보낼 때다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "친구·연인과 사진 콘셉트를 같이 정할 때 기분이 좋다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "내가 원하는 사진 콘셉트를 양보해야 하더라도, 일행과 함께 단체 사진을 잘 챙기는 건 내 의무다." },
      { lens: "L4", scaleName: "Individualism vs Collectivism", scale: "5점 동의", q: "같이 간 일행이 정한 포토부스 콘셉트나 프레임 결정을 존중하는 게 중요하다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "사진 인쇄를 많이 하는 편보다 적게 하는 편이다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "인쇄한 사진 중에 마음에 드는 것만 남기고 나머지는 정리한다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "사진은 많이 찍기보다 마음에 드는 한두 장이 더 가치 있다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "충동적으로 매장 들어가서 찍는 일이 거의 없다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "화려한 컨셉보다 단순한 톤(흑백·미니멀)에 더 끌린다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "보정·필터를 세게 쓰기보다 자연스럽게 두는 편이다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "매장도 화려한 곳보다 차분한 분위기의 곳을 좋아한다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "사진 프레임에 소품·스티커가 너무 많으면 부담스럽다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "내가 어떤 사진을 가지고 있는지 기억하고 있다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "사진을 인쇄할 때 어떤 컷을 고를지 신중하게 본다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "이 매장을 갈지 말지 미리 따져보고 결정한다." },
      { lens: "L5", scaleName: "Consumer Minimalism", scale: "5점 동의", q: "내가 인쇄해서 가진 사진들은 다 이유가 있어서 가지고 있다." },
      { lens: "L6", scaleName: "Discount Rate (인내심)", scale: "선택", q: "\"1주 뒤 한정 콘셉트 매장 8,900원\" vs \"오늘 일반 콘셉트 매장 X원\" — 어느 쪽을 선택하시겠습니까?" },
      { lens: "L6", scaleName: "Discount Rate (인내심)", scale: "선택", q: "\"2주 뒤 새 매장 오픈 기념 7,900원\" vs \"오늘 일반 매장 X원\" — 어느 쪽을 선택하시겠습니까?" },
      { lens: "L6", scaleName: "Present Bias (지금 받기 욕구)", scale: "선택", q: "\"1주 뒤 예약 후 무대기로 촬영\" vs \"지금 X분 줄서서 촬영\" — 어느 쪽을 선택하시겠습니까?" },
      { lens: "L6", scaleName: "Present Bias (지금 받기 욕구)", scale: "선택", q: "\"다음주 예약 무대기 9,900원\" vs \"지금 30분 줄서서 X원\" — 어느 쪽을 선택하시겠습니까?" },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "포토이즘 갈 때 미리 예약하는 편이다." },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "어떤 콘셉트를 찍을지 미리 정해두고 가는 편이다." },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "새 매장 갈 때 후기·인스타를 미리 충분히 본다." },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "포토이즘 가는 시간을 미리 일정에 잡아둔다." },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "포토이즘은 보통 즉흥적으로 결정한다." },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "찍은 사진을 어디에 둘지 미리 정해두지 않는다." },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "포토이즘 갈 시간을 미리 짜두지 않는다." },
      { lens: "L6", scaleName: "Conscientiousness (계획성)", scale: "3점 척도", q: "예약하는 일은 거의 없다." },
      { lens: "L6", scaleName: "도메인 맞춤형 추가 (신컨셉 채택·시간 앵커·결정-실행 시간)", scale: "4점 척도", q: "포토이즘이 신콘셉트를 출시했을 때 본인은 보통 어떻게 하시나요?" },
      { lens: "L6", scaleName: "도메인 맞춤형 추가 (신컨셉 채택·시간 앵커·결정-실행 시간)", scale: "8점 척도", q: "포토이즘 갈 때 보통 어떤 계기인가요? 해당되는 것을 모두 골라 주세요." },
      { lens: "L6", scaleName: "도메인 맞춤형 추가 (신컨셉 채택·시간 앵커·결정-실행 시간)", scale: "5점 척도", q: "최근 1회" },
      { lens: "L6", scaleName: "도메인 맞춤형 추가 (신컨셉 채택·시간 앵커·결정-실행 시간)", scale: "5점 척도", q: "최근 2회" },
      { lens: "L6", scaleName: "도메인 맞춤형 추가 (신컨셉 채택·시간 앵커·결정-실행 시간)", scale: "5점 척도", q: "최근 3회" },
    ],
  },
] as const;

/** 인터뷰 — 사용자 제공 가이드 (Part A~D). */
export const DEMO_INTERVIEW = {
  title: '심층 인터뷰 (1종, 약 60분)',
  desc: '소비 인생사·자기 인식·포토부스 도메인·카테고리별 자기 변화',
  parts: [
    {
      part: 'A',
      title: '소비 인생사 + 가치관 (15분)',
      questions: [
        '최근 1년 가장 후회한 구매와 가장 만족한 구매는?',
        '돈 쓰기 가장 아까운 영역과 안 아까운 영역은?',
        '친환경·가격·품질·브랜드 중 가장 중요한 것은?',
      ],
    },
    {
      part: 'B',
      title: '자기 인식 — 결정 스타일·영향원·욕망 (15분)',
      questions: [
        '본인이 결정할 때 어떤 스타일이라고 생각하세요? 빠르게 직감? 충분히 비교?',
        '본인이 가장 영향을 많이 받는 사람·정보원은?',
        '본인은 기다림에 강한 편이에요, 약한 편이에요?',
      ],
    },
    {
      part: 'C',
      title: '포토부스 도메인 인터뷰 (15~20분)',
      questions: [
        '최근 포토이즘 또는 포토부스에 갔던 3번 — 누구랑·언제·왜·만족도는?',
        '그 중 가장 만족했던 것 / 가장 별로였던 것은?',
        '사진은 어떻게 처리해요? (인스타·저장·프린트)',
        '포토이즘에 안 갈 것 같은 상황은?',
      ],
    },
    {
      part: 'D',
      title: '카테고리별 자기 변화 (10~15분)',
      questions: [
        '평소와 다르게 행동하는 카테고리·상황이 있어요? (충동적이거나 신중한 카테고리)',
      ],
    },
  ],
} as const;

/** 3단계 — mock 수집 결과 (데이터는 별도 수집 설정) */
export const DEMO_COLLECTION = {
  consumptionResponses: 412,
  domainResponses: 388,
  interviews: 24,
  note: '※ 데모에서는 수집 과정을 생략하고, 사전 수집된 응답으로 에이전트를 구성합니다.',
} as const;

/** 5단계 — FGI 시나리오 (포토이즘 재방문율, 3라운드 고정 데모 시나리오)
 *
 * 데모 reproducibility 를 위해 라운드 수·주제·각 라운드의 goal_question 을 hardcode.
 * 실제 응용에서는 사용자가 토론 주제를 입력하고 AI 가 라운드를 동적 생성한다.
 */
export const DEMO_FGI_TOPIC =
  '가격대가 비슷한 경쟁사들 사이에서, 포토이즘의 IP 프레임이 실제로 재방문을 유도하는지 그리고 앱 활용도를 어떻게 높일 수 있을지';

export const DEMO_FGI_MAX_ROUNDS = 3;

/** 데모 FGI 라운드 (R1~R3 고정) — frontend 가 backend 에 그대로 보내는 SuggestedRound[]. */
export const DEMO_FGI_ROUNDS = [
  {
    round: 1,
    subtopic: '브랜드 선택 요인 · IP 프레임',
    goal_question:
      '셀프 사진관 브랜드들이 대부분 비슷한 가격대(2컷 5천원·4컷 1만원)인데, 어떤 기준으로 브랜드를 선택하시나요? 포토이즘을 선택하는 결정적 이유와 IP 프레임(캐릭터·아이돌 콜라보)의 역할을 말씀해주세요.',
    probes: [
      '콜라보가 없는 시기에도 포토이즘에 가시는지',
      '콜라보 정보를 어디서 어떻게 접하는지',
      '"포토이즘에 다시 안 가게 되는" 이유가 있다면 무엇인지',
    ],
  },
  {
    round: 2,
    subtopic: '매장 환경 · 인스타 업로드 사이클',
    goal_question:
      '포토이즘 매장 분위기·소품·조명이 재방문에 영향을 주나요? 그리고 찍은 사진을 SNS(특히 인스타)에 업로드한 경험이 다시 방문하게 만드는 데 어떤 작용을 했는지 구체적으로 말씀해주세요.',
    probes: [
      '콜라보 프레임 vs 일반 프레임 — 업로드 빈도 차이',
      '친구 반응이 다음 방문 의도에 미친 영향',
      'SNS 를 잘 안 쓰는 경우 재방문 동기가 어디서 생기는지',
    ],
  },
  {
    round: 3,
    subtopic: '포토이즘 앱 · 리텐션 메커니즘',
    goal_question:
      '포토이즘 앱을 설치해보신 적이 있나요? 있다면 어떤 기능을 주로 쓰고, 없다면 왜 안 깔았는지요. 앱에 "콜라보 캘린더", "사전 알림", "매장 예약" 같은 기능이 있다면 재방문에 도움이 될지 알고 싶어요.',
    probes: [
      '앱이 "사진 다운로드 도구" 외에 어떤 기능이 있는지 인지하는지',
      '어떤 기능이 있어야 앱을 다시 열게 될지',
      '푸시 알림에 대한 태도 (광고 피로 vs 정보 가치)',
    ],
  },
] as const;

/** 가이드 단계 정의 */
export const DEMO_STEPS = [
  { n: 1, key: 'brief', label: '기업 의뢰 접수' },
  { n: 2, key: 'survey', label: '설문 설계' },
  { n: 3, key: 'collect', label: '패널 데이터 수집' },
  { n: 4, key: 'agents', label: 'AI 에이전트 + 평가·대화' },
  { n: 5, key: 'fgi', label: 'FGI 진행' },
  { n: 6, key: 'report', label: '인사이트 보고서' },
  { n: 7, key: 'deliver', label: '보고서 제공' },
] as const;
